#include <string>

namespace embed {
const constexpr inline std::string_view balk_json = R"EOF(
{
  "version": "0.0.1",
  "unchangable_settings": {
    "project": "",
    "language": "C++",
    "meta_build_system": "cmake"
  },
  "settings": {
    "binary": "executable",
    "build_system": "ninja",
    "toolchain": "clang",
    "formatter": "",
    "linter": "",

    "default_profile": "debug",

    "cmake": {
      "path": "cmake",
      "configure_arguments": [],
      "build_arguments": []
    }
  },
  "directories": {
    "balk_path": "balk",
    "build_path": "build",
    "build_examples_path": "examples",
    "build_tests_path": "tests",
    "build_benchmarks_path": "benchmarks",
    "cmake_path": "cmake",
    "examples_path": "examples",
    "export_path": "export",
    "headers_path": "headers",
    "source_path": "source",
    "tests_path": "tests",
    "benchmarks_path": "benchmarks"
  },
  "format": {
    "clang-fmt": {
      "binary": "clang-fmt",
      "preappended_arguments": [],
      "appended_arguments": []
    },
    "astyle": {
      "binary": "astyle",
      "preappended_arguments": [],
      "appended_arguments": []
    }
  },
  "lint": {
    "clang-check": {
      "binary": "clang-check",
      "preappended_arguments": [],
      "appended_arguments": []
    }
  },
  "build_systems": {
    "make": {
      "build_type": "Unix Makefile",
      "path": "make"
    },
    "ninja": {
      "build_type": "Ninja",
      "path": "ninja"
    }
  },
  "toolchains": {
    "gcc": {
      "c_compiler": "gcc",
      "cpp_compiler": "g++",
      "linker": "ld",
      "assembler": "as"
    },
    "clang": {
      "c_compiler": "clang",
      "cpp_compiler": "clang++",
      "linker": "ld",
      "assembler": "clang"
    },
    "msvc": {
      "c_compiler": "cl",
      "cpp_compiler": "cl",
      "linker": "link",
      "assembler": "ml"
    }
  },
  "commands": {
    "fetch": {
      "binary": "balk",
      "preappended_arguments": [
        "internal",
        "fetch"
      ],
      "appended_arguments": []
    }
  },
  "profiles": {
    "debug": {
      "path_within_build": "debug",
      "cmake_build_type": "Debug",
      "override_settings": {
      }
    },
    "release": {
      "path_within_build": "release",
      "cmake_build_type": "Release",
      "override_settings": {
      }
    }
  }
}
)EOF";

const constexpr inline std::string_view cmakelists_txt = R"EOF(
cmake_minimum_required(VERSION 3.28)
project("${BALK_UNCHANGABLE_SETTINGS_PROJECT}")
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS ON)


# This is your CMakeLists.txt file. It defines how to build your project.
# Balk will not modify this file at any point.
# Other files you write describing the build should be placed in the cmake/.
# Files generated by Balk are placed in balk/ and should not be edited by hand because they may change at any time.
# Building anything regenerates your cmake build whenever CMakeLists.txt, any file under cmake/, or any file under balk/ changes.


# A number of variables describing the current build are set when CMake is ran.
# Every project starts with the same CMake files so these variables control what is built.
# Any variable in CMake beginning with CMAKE_ is set by CMake itself.
# Any variable in CMake beginning with BALK_ is a configuration option you can control.
# Pass the --verbose flag (when using build) to see the CMake invocation.
# alsoe, see the (mostly complete) list of variables at https://....
# Some of the most important are:
#   BALK_UNCHANGABLE_SETTINGS_PROJECT              Project name
#   BALK_SETTINGS_BINARY               Built binary (executable, archive, shared)
#   BALK_PROFILE              Selected profile (debug, release, or something else)
#   CMAKE_SYSTEM_NAME          Target operating system to compile for
#   CMAKE_SYSTEM_PROCESSOR     Target processor (architecture) to compile for



# set compilation options based on profile, generator, toolchain, etc...
include("${BALK_DIRECTORIES_CMAKE}/compilation.cmake")

# path to header/ directory exposed through the variable ${balk_header_files}
include("${BALK_DIRECTORIES_CMAKE}/headers.cmake")

# list of module files under source/ exposed as a library through the variable ${balk_modules}
include("${BALK_DIRECTORIES_CMAKE}/modules.cmake")

# fetch source code with git using the custom command: `balk command fetch`
# fetched libraries exposed through the variable ${balk_FetchContent}
include("${BALK_DIRECTORIES_CMAKE}/fetch.cmake")



# build binary
include("${BALK_DIRECTORIES_CMAKE}/build_binary.cmake")

# build tests if enabled
include("${BALK_DIRECTORIES_CMAKE}/build_tests.cmake")

# build examples if enabled
include("${BALK_DIRECTORIES_CMAKE}/build_examples.cmake")

# build benchmarks if enabled
include("${BALK_DIRECTORIES_CMAKE}/build_benchmarks.cmake")

# custom targets built before commands are run
# targets: build run test example export clean format lint
include("${BALK_DIRECTORIES_CMAKE}/command_targets.cmake")
)EOF";

namespace sources {
const constexpr inline std::string_view main_cpp = R"EOF(
#include <cstdlib>

// This is your main program
int main() {
    return EXIT_SUCCESS;
}
)EOF";
}

namespace benchmarks {
const constexpr inline std::string_view benchmark_cpp = R"EOF(
#include <cstdlib>

// This is a benchmark
// Every cpp file in benchmarks is a separate program
int main() {
    return EXIT_SUCCESS;
}
)EOF";
}

namespace examples {
const constexpr inline std::string_view example_cpp = R"EOF(
#include <cstdlib>

// This is a example
// Every cpp file in examples is a separate program
int main() {
    return EXIT_SUCCESS;
}
)EOF";
}

namespace tests {
const constexpr inline std::string_view test_cpp = R"EOF(
#include <cstdlib>

// This is a test
// Every cpp file in tests is a separate program
int main() {
    return EXIT_SUCCESS;
}
)EOF";
}

namespace cmake {
const constexpr inline std::string_view build_benchmarks_cmake = R"EOF(
if(EXISTS "${BALK_DIRECTORIES_BENCHMARKS}")
    file(
        GLOB_RECURSE
        balk_benchmark_files
        CONFIGURE_DEPENDS
        "${BALK_DIRECTORIES_BENCHMARKS}/*.cpp"
        "${BALK_DIRECTORIES_BENCHMARKS}/*.cc"
        "${BALK_DIRECTORIES_BENCHMARKS}/*.cxx"
        "${BALK_DIRECTORIES_BENCHMARKS}/*.c++"
    )

    add_custom_target(benchmarks)

    foreach(source_file ${balk_benchmark_files})
        # Get the path relative to the benchmarks source directory
        cmake_path(
            RELATIVE_PATH source_file
            BASE_DIRECTORY "${BALK_DIRECTORIES_BENCHMARKS}"
            OUTPUT_VARIABLE rel_path
        )
    
        # Strip the .cpp extension
        string(REGEX REPLACE "\\.cpp$" "" target_rel_path "${rel_path}")
        string(REGEX REPLACE "\\.cc$" "" target_rel_path "${rel_path}")
        string(REGEX REPLACE "\\.cxx$" "" target_rel_path "${rel_path}")
        string(REGEX REPLACE "\\.c\\+\\+$" "" target_rel_path "${rel_path}")
    
        # Replace slashes with safe characters if needed
        string(REPLACE "/" "_" target_name "benchmark_${target_rel_path}")
    
        add_executable(${target_name} EXCLUDE_FROM_ALL "${source_file}")

        # Preserve the directory structure in the binary output directory
        # e.g., ${BALK_DIRECTORIES_BUILD_BENCHMARKS}/a/b/c/d.exe (or without .exe extension on Linux/Mac)
        get_filename_component(target_output_dir "${BALK_DIRECTORIES_BUILD_BENCHMARKS}/${rel_path}" DIRECTORY)
        get_filename_component(target_output_name "${rel_path}" NAME_WE)
    
        set_target_properties(
            ${target_name} PROPERTIES
            RUNTIME_OUTPUT_DIRECTORY "${target_output_dir}"
            OUTPUT_NAME "${target_output_name}"
        )
    
        target_include_directories(${target_name} PRIVATE "${balk_header_files}")

        if(balk_modules_files)
            target_link_libraries(${target_name} PRIVATE balk_modules balk_FetchContent)
        else()
            target_link_libraries(${target_name} PRIVATE balk_FetchContent)
        endif()

        add_dependencies(benchmarks ${target_name})
    endforeach()
endif()
)EOF";

const constexpr inline std::string_view build_binary_cmake = R"EOF(
if("${BALK_SETTINGS_BINARY}" STREQUAL "executable")
    add_executable(${PROJECT_NAME})
elseif("${BALK_SETTINGS_BINARY}" STREQUAL "archive")
    add_library(${PROJECT_NAME} STATIC)
elseif("${BALK_SETTINGS_BINARY}" STREQUAL "shared")
    add_library(${PROJECT_NAME} SHARED)
else()
    message(FATAL_ERROR "Not building an executable, archive, or shared binary! Maybe an issue!")
endif()

target_include_directories(${PROJECT_NAME} PRIVATE "${balk_header_files}")

file(
    GLOB_RECURSE
    balk_source_files
    CONFIGURE_DEPENDS
    "${BALK_DIRECTORIES_SOURCE}/*.cpp"
    "${BALK_DIRECTORIES_SOURCE}/*.cc"
    "${BALK_DIRECTORIES_SOURCE}/*.cxx"
    "${BALK_DIRECTORIES_SOURCE}/*.c++"
)
target_sources(
    ${PROJECT_NAME}
    PRIVATE ${balk_source_files}
)

if(balk_modules_files)
    target_link_libraries(${PROJECT_NAME} PRIVATE balk_modules balk_FetchContent)
else()
    target_link_libraries(${PROJECT_NAME} PRIVATE balk_FetchContent)
endif()
)EOF";

const constexpr inline std::string_view build_examples_cmake = R"EOF(
if(EXISTS "${BALK_DIRECTORIES_EXAMPLES}")
    file(
        GLOB_RECURSE
        balk_example_files
        CONFIGURE_DEPENDS
        "${BALK_DIRECTORIES_EXAMPLES}/*.cpp"
        "${BALK_DIRECTORIES_EXAMPLES}/*.cc"
        "${BALK_DIRECTORIES_EXAMPLES}/*.cxx"
        "${BALK_DIRECTORIES_EXAMPLES}/*.c++"
    )

    add_custom_target(examples)

    foreach(source_file ${balk_example_files})
        # Get the path relative to the examples source directory
        cmake_path(
            RELATIVE_PATH source_file
            BASE_DIRECTORY "${BALK_DIRECTORIES_EXAMPLES}"
            OUTPUT_VARIABLE rel_path
        )
    
        # Strip the .cpp extension
        string(REGEX REPLACE "\\.cpp$" "" target_rel_path "${rel_path}")
        string(REGEX REPLACE "\\.cc$" "" target_rel_path "${rel_path}")
        string(REGEX REPLACE "\\.cxx$" "" target_rel_path "${rel_path}")
        string(REGEX REPLACE "\\.c\\+\\+$" "" target_rel_path "${rel_path}")
    
        # Replace slashes with safe characters if needed
        string(REPLACE "/" "_" target_name "example_${target_rel_path}")
    
        add_executable(${target_name} EXCLUDE_FROM_ALL "${source_file}")

        # Preserve the directory structure in the binary output directory
        # e.g., ${BALK_DIRECTORIES_BUILD_EXAMPLES}/a/b/c/d.exe (or without .exe extension on Linux/Mac)
        get_filename_component(target_output_dir "${BALK_DIRECTORIES_BUILD_EXAMPLES}/${rel_path}" DIRECTORY)
        get_filename_component(target_output_name "${rel_path}" NAME_WE)
    
        set_target_properties(
            ${target_name} PROPERTIES
            RUNTIME_OUTPUT_DIRECTORY "${target_output_dir}"
            OUTPUT_NAME "${target_output_name}"
        )
    
        target_include_directories(${target_name} PRIVATE "${balk_header_files}")

        if(balk_modules_files)
            target_link_libraries(${target_name} PRIVATE balk_modules balk_FetchContent)
        else()
            target_link_libraries(${target_name} PRIVATE balk_FetchContent)
        endif()

        add_dependencies(examples ${target_name})
    endforeach()
endif()
)EOF";

const constexpr inline std::string_view build_tests_cmake = R"EOF(
if(EXISTS "${BALK_DIRECTORIES_TESTS}")
    file(
        GLOB_RECURSE
        balk_test_files
        CONFIGURE_DEPENDS
        "${BALK_DIRECTORIES_TESTS}/*.cpp"
        "${BALK_DIRECTORIES_TESTS}/*.cc"
        "${BALK_DIRECTORIES_TESTS}/*.cxx"
        "${BALK_DIRECTORIES_TESTS}/*.c++"
    )

    add_custom_target(tests)

    foreach(source_file ${balk_test_files})
        # Get the path relative to the tests source directory
        cmake_path(
            RELATIVE_PATH source_file
            BASE_DIRECTORY "${BALK_DIRECTORIES_TESTS}"
            OUTPUT_VARIABLE rel_path
        )
    
        # Strip the .cpp extension
        string(REGEX REPLACE "\\.cpp$" "" target_rel_path "${rel_path}")
        string(REGEX REPLACE "\\.cc$" "" target_rel_path "${rel_path}")
        string(REGEX REPLACE "\\.cxx$" "" target_rel_path "${rel_path}")
        string(REGEX REPLACE "\\.c\\+\\+$" "" target_rel_path "${rel_path}")
    
        # Replace slashes with safe characters if needed
        string(REPLACE "/" "_" target_name "test_${target_rel_path}")
    
        add_executable(${target_name} EXCLUDE_FROM_ALL "${source_file}")

        # Preserve the directory structure in the binary output directory
        # e.g., ${BALK_DIRECTORIES_BUILD_TESTS}/a/b/c/d.exe (or without .exe extension on Linux/Mac)
        get_filename_component(target_output_dir "${BALK_DIRECTORIES_BUILD_TESTS}/${rel_path}" DIRECTORY)
        get_filename_component(target_output_name "${rel_path}" NAME_WE)
    
        set_target_properties(
            ${target_name} PROPERTIES
            RUNTIME_OUTPUT_DIRECTORY "${target_output_dir}"
            OUTPUT_NAME "${target_output_name}"
        )
    
        target_include_directories(${target_name} PRIVATE "${balk_header_files}")

        if(balk_modules_files)
            target_link_libraries(${target_name} PRIVATE balk_modules balk_FetchContent)
        else()
            target_link_libraries(${target_name} PRIVATE balk_FetchContent)
        endif()

        add_dependencies(tests ${target_name})
    endforeach()
endif()
)EOF";

const constexpr inline std::string_view command_targets_cmake = R"EOF(
add_custom_target(
    build
    DEPENDS ${PROJECT_NAME}
)

add_custom_target(
    run
    DEPENDS build
)

add_custom_target(
    export
    COMMAND ${CMAKE_COMMAND} -E make_directory "${BALK_DIRECTORIES_EXPORT}/${BALK_PROFILE}/${PROJECT_NAME}"
    COMMAND ${CMAKE_COMMAND} -E copy "${CMAKE_BINARY_DIR}/${PROJECT_NAME}" "${BALK_DIRECTORIES_EXPORT}/${BALK_PROFILE}/${PROJECT_NAME}"
    DEPENDS ${PROJECT_NAME}
)

# CMake already defines a clean target
#add_custom_target(
    #clean
#)

add_custom_target(
    format
)

add_custom_target(
    lint
)
)EOF";

const constexpr inline std::string_view compilation_cmake = R"EOF(
# control warning settings
if(${BALK_TOOLCHAIN} STREQUAL "msvc")
    add_compile_options(/W4)
elseif(${BALK_TOOLCHAIN} STREQUAL "gcc")
    add_compile_options(-Wall -Wextra -Wpedantic)
elseif(${BALK_TOOLCHAIN} STREQUAL "clang")
    add_compile_options(-Wall -Wextra -Wpedantic)
else()
endif()
)EOF";

const constexpr inline std::string_view fetch_cmake = R"EOF(
include(FetchContent)

set(FETCHCONTENT_BASE_DIR "${CMAKE_SOURCE_DIR}/fetch")
add_library(balk_FetchContent INTERFACE)

file(
    GLOB_RECURSE CMAKE_FETCH_FILES CONFIGURE_DEPENDS
    "${BALK_DIRECTORIES_CMAKE}/fetch/*.cmake"
)

foreach(CMAKE_FETCH_FILE ${CMAKE_FETCH_FILES})
    include("${CMAKE_FETCH_FILE}")
endforeach()
)EOF";

const constexpr inline std::string_view headers_cmake = R"EOF(
set(balk_header_files "${BALK_DIRECTORIES_HEADERS}")
)EOF";

const constexpr inline std::string_view modules_cmake = R"EOF(
file(
    GLOB_RECURSE balk_modules_files CONFIGURE_DEPENDS
   "${BALK_DIRECTORIES_SOURCE}/*.cppm"
)

if(balk_modules_files)
    # only true when balk_modules_files detects one or more files

    # make sure compiler supports modules
    include("${BALK_DIRECTORIES_CMAKE}/module_test_capability.cmake")

    add_library(balk_modules)

    target_compile_features(balk_modules PUBLIC cxx_std_20)

    target_include_directories(balk_modules PRIVATE "${balk_header_files}")

    target_sources(
        balk_modules
        PUBLIC
        FILE_SET CXX_MODULES
        TYPE CXX_MODULES
        FILES ${balk_modules_files}
    )

    target_link_libraries(balk_modules PRIVATE balk_FetchContent)
else()
    add_library(balk_modules INTERFACE)

    target_compile_features(balk_modules INTERFACE cxx_std_20)
endif()
)EOF";

const constexpr inline std::string_view module_test_capability_cmake = R"EOF(
include(CMakePushCheckState)

set(CMAKE_CXX_SCAN_FOR_MODULES ON)

set(CXX_MODULE_TEST_DIR "${CMAKE_BINARY_DIR}/module_test_capability")

file(WRITE "${CXX_MODULE_TEST_DIR}/CMakeLists.txt" [=[
cmake_minimum_required(VERSION 3.28)

project(cxx_module_test LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

add_library(test_module)
target_sources(test_module
    PUBLIC
        FILE_SET CXX_MODULES
        FILES
            test.cppm
)
]=])

file(WRITE "${CXX_MODULE_TEST_DIR}/test.cppm" [=[
export module test;

export int answer()
{
    return 42;
}
]=])

try_compile(
    HAS_CXX20_MODULES
    "${CMAKE_BINARY_DIR}/cxx_module_test_build"
    "${CXX_MODULE_TEST_DIR}"
    cxx_module_test
    OUTPUT_VARIABLE CXX_MODULE_TEST_OUTPUT
)
)EOF";
}
}
